### ISSUE TITLE
Example does not work

### ISSUE THREAD

**Issue by gerwinbrunner** [CodeAdventure/space-ui#18]
Hi Dominik,

could it be that the example app is broken with the current release of meteor (1.0.3.2)?
Just checked it out and tried to start it and I get the following error:
````
W20150312-14:26:03.534(1)? (STDERR)           
W20150312-14:26:03.536(1)? (STDERR) /Users/ap/.meteor/packages/meteor-tool/.1.0.36.dkfy8t++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:173
W20150312-14:26:03.536(1)? (STDERR) 						throw(ex);
W20150312-14:26:03.537(1)? (STDERR) 						      ^
W20150312-14:26:03.537(1)? (STDERR) TypeError: Cannot read property 'Command' of undefined
W20150312-14:26:03.537(1)? (STDERR)     at shared/lib/commands.coffee:2:51
W20150312-14:26:03.537(1)? (STDERR)     at /Users/ap/Documents/workspaces/github-workspace/space-ui/examples/TodoMVC/.meteor/local/build/programs/server/app/shared/lib/commands.coffee.js:31:3
W20150312-14:26:03.537(1)? (STDERR)     at /Users/ap/Documents/workspaces/github-workspace/space-ui/examples/TodoMVC/.meteor/local/build/programs/server/boot.js:168:10
W20150312-14:26:03.537(1)? (STDERR)     at Array.forEach (native)
W20150312-14:26:03.537(1)? (STDERR)     at Function._.each._.forEach (/Users/ap/.meteor/packages/meteor-tool/.1.0.36.dkfy8t++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
W20150312-14:26:03.538(1)? (STDERR)     at /Users/ap/Documents/workspaces/github-workspace/space-ui/examples/TodoMVC/.meteor/local/build/programs/server/boot.js:82:5
=
````

Cheers,
Gerwin

**Comment by DominikGuzei** [comment]
Hey Gerwin!
it should work now, sorry I forgot to update the example to use space:ui@4.0.1 version :wink:
